### ISSUE TITLE
I have a question about personium configuration. 

### ISSUE THREAD

**Issue by dearyu79** [personium/personium-engine#145]
Hello!
I am Jung from Korea. I have question about attached file. 

(Q.1) Is it correct that the process behaves according to the number(1~7) indicated in the attached file?

(Q.2) What is the communication interface(way) between Personium-engine and nginx? (ex) "http port 80" etc

(Q.3) How does 'Active M' running? (sync or async)

Please let us know the question.

![Process](https://user-images.githubusercontent.com/83572706/116850994-95669a80-ac2c-11eb-9049-308eb0ae1139.PNG)

**Comment by tochi-y** [comment]
Hello, Jung!
Sorry for late reply. We had long public holidays in Japan, so I missed this issue.

> (Q.1) Is it correct that the process behaves according to the number(1~7) indicated in the attached file?

The order is almost right.
The number (3~7) will be executed only when necessary depending on the process.

> (Q.2) What is the communication interface(way) between Personium-engine and nginx? (ex) "http port 80" etc

From engine to nginx, https port 443 is used.

> (Q.3) How does 'Active M' running? (sync or async)

Between core and ActiveMQ, Publisher-Subscriber model works there. That's async.

**Comment by dixonsiu** [comment]
Close the issue because there are no further questions.
