### ISSUE TITLE
CSV parser support

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-engine#63]
It would be nice to use a library like [this](https://github.com/knrz/CSV.js) to support parsing and exporting of CSV  file within the Engine Script.

**Comment by yoh1496** [comment]
Hi @dixonsiu  

How about using [Papa Parse](https://www.papaparse.com/) ?

After approving #148, we can use Papa Parse like below.

 ```javascript
function csvtest(request) {
  const Papa = require("./papaparse.min");
  const dat= Papa.parse("aaa,bbb,ccc\nhoge,foo,bar\n111,222,333", {header: true});
  return {
    status: 200,
    headers: { "Content-Type": "application/json" },
    body: [
      JSON.stringify(dat),
    ],
  };
}
```

![image](https://user-images.githubusercontent.com/4243145/125742745-62a6a75b-863e-4f72-8c4f-878c215bd831.png)

**Comment by dixonsiu** [comment]
Yes, I was already using [papaparse ](https://github.com/dixonsiu/app-cst-survey/blob/master/bar/90_contents/Engine/__src/papaparse.js)by modifying the first line.

```
exports.Papa = (function(root, factory)
```

**Comment by yoh1496** [comment]
Oh sorry. I don't know that you solved it already.
Could you close this issue?

By the way, the modifying lines is not good in perspective of maintainability 😭

**Comment by dixonsiu** [comment]
Yup, hopefully, with your pull request, I don't have to write the silly one line anymore.
