### ISSUE TITLE
Upgrade Rhino version so that ES6 functions can be used

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-engine#70]
Currently, [Luxon](https://moment.github.io/luxon/) does not work since it uses several ES6 functions.

**Comment by shimono** [comment]
Currently 1.7.7 is used.
https://github.com/personium/personium-engine/blob/master/pom.xml#L110

Some improvements can be expected by upgrading to 1.7.10 
https://mozilla.github.io/rhino/compat/engines.html
