### ISSUE TITLE
Engine Timeout

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium-engine#71]
After parsing the CSV file, the operations of adding 10000 entries to DB has triggered the [Script Timeout Error](https://github.com/personium/personium-engine/blob/b3a7f92937a667a2f7e71ae70c70a52da14233fc/src/main/java/io/personium/engine/PersoniumEngineContext.java#L270) .

If we cannot set [Timeout value](https://github.com/personium/personium-engine/blob/b3a7f92937a667a2f7e71ae70c70a52da14233fc/src/main/java/io/personium/engine/PersoniumJsContextFactory.java#L34) dynamically, then maybe we have to find a way to execute time consuming script offline. (AJAX like function in the Engine)

**Comment by SawamiWataru** [comment]
Released v1.5.21.
